"use client";

import { Building2, CheckCircle2, Factory, History, MapPin, Network, PackageCheck, Play, Store, Truck, Waves, Warehouse } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useRunSimulation, useScenario, useSimulation } from "@/hooks/use-resilichain-data";

const progressSteps = ["Loading historical snapshot", "Evaluating road flood exposure", "Mapping supply-chain dependencies", "Identifying affected orders", "Generating operational impact"];

export function ScenarioPage() {
  const scenario = useScenario(); const run = useRunSimulation(); const simulation = useSimulation(run.data?.id ?? ""); const router = useRouter();
  const [step, setStep] = useState(-1);
  useEffect(() => { if (step < 0 || step >= progressSteps.length) return; const timer = window.setTimeout(() => setStep((value) => value + 1), 420); return () => window.clearTimeout(timer); }, [step]);
  useEffect(() => { if (step === progressSteps.length && run.data && simulation.data?.status === "completed") router.push(`/disruption?simulation=${run.data.id}`); }, [step, run.data, simulation.data?.status, router]);
  const counts = useMemo(() => { const data = scenario.data; return data ? { suppliers: data.facilities.filter((x) => x.kind === "supplier").length, factories: data.facilities.filter((x) => x.kind === "factory").length, warehouses: data.facilities.filter((x) => x.kind === "warehouse").length, stores: data.facilities.filter((x) => x.kind === "store").length } : null; }, [scenario.data]);
  const start = () => { if (!scenario.data) return; setStep(0); run.mutate(scenario.data.id); };

  return <AppShell>
    <div className="relative p-4 md:p-8">
      {scenario.isLoading && <LoadingState label="Loading historical scenarioâ€¦" />}
      {scenario.isError && <ErrorState message={scenario.error.message} onRetry={() => void scenario.refetch()} />}
      {scenario.data && counts && <>
        <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="page-title">Supply Chain Scenario</h1><p className="mt-1 max-w-2xl text-sm text-muted">Evaluate how a historical flood event could affect production, distribution, and order fulfillment.</p></div><button onClick={start} disabled={step >= 0 || run.isPending} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-primary-dark disabled:cursor-not-allowed disabled:opacity-60"><Play size={18} fill="currentColor" /> Run Simulation</button></div>
        {scenario.data.dataSources.historicalStatus === "offline_snapshot" && <div className="mb-5 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><strong>Historical Snapshot Mode.</strong> Live external data unavailable. Simulation is using the locally stored historical snapshot.</div>}
        <div className="grid gap-6 xl:grid-cols-2">
          <section className="card flex min-h-[560px] flex-col p-6"><div className="mb-4 flex items-center gap-2 border-b border-outline pb-3"><History className="text-primary" size={20} /><h2 className="section-title">Historical Flood Scenario</h2></div><div className="mb-4"><div className="eyebrow mb-2">Selected Scenario</div><div className="flex items-center justify-between rounded-lg border border-secondary-soft bg-secondary-soft/30 p-3 font-semibold"><span>{scenario.data.name}</span><CheckCircle2 size={18} className="text-primary" /></div></div>
            <div className="mb-4 grid grid-cols-1 gap-2 sm:grid-cols-3">{[["Location", scenario.data.location, MapPin], ["Event type", scenario.data.eventType, Waves], ["Mode", "Historical Replay", History]].map(([label, value, Icon]) => { const I = Icon as typeof MapPin; return <div key={String(label)} className="rounded-lg border border-outline/60 bg-surface-low p-3"><div className="eyebrow mb-1">{String(label)}</div><div className="mono flex items-center gap-1 text-xs font-semibold"><I size={15} />{String(value)}</div></div>; })}</div>
            <div className="relative flex min-h-[270px] flex-1 overflow-hidden rounded-lg border border-outline bg-[linear-gradient(135deg,#e4edf0,#f5f7f6_45%,#dcebe7)]"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(#94a3b822_1px,transparent_1px),linear-gradient(90deg,#94a3b822_1px,transparent_1px)] [background-size:28px_28px]" /><div className="absolute left-[14%] top-[18%] h-36 w-52 rotate-[-8deg] rounded-[45%] bg-danger/15 blur-sm" /><div className="absolute left-3 top-3 flex items-center gap-2 rounded-md border border-outline bg-white/90 px-2 py-1 text-[10px] font-semibold uppercase text-muted shadow-sm"><span className="h-2 w-2 rounded-full bg-danger" /> Historical high-impact zone</div><div className="relative m-auto text-center"><MapPin className="mx-auto mb-2 text-primary" /><div className="text-sm font-semibold">Jakarta pilot area</div><div className="mono text-[10px] text-muted">Stored historical flood context</div></div></div>
          </section>
          <section className="card flex min-h-[560px] flex-col p-6"><div className="mb-4 flex items-center justify-between gap-3 border-b border-outline pb-3"><div className="flex items-center gap-2"><Network className="text-primary" size={20} /><h2 className="section-title">Demo Supply Chain â€” {scenario.data.companyName}</h2></div><span className="eyebrow rounded bg-surface-high px-2 py-1">Simulated Operational Data</span></div>
            <div className="mb-6 grid grid-cols-2 gap-2 sm:grid-cols-3">{[[counts.suppliers, "Suppliers", Truck], [counts.factories, "Factory", Factory], [counts.warehouses, "Warehouses", Warehouse], [scenario.data.vehicles.length, "Vehicles", Building2], [counts.stores, "Stores", Store], [scenario.data.orders.length, "Active Orders", PackageCheck]].map(([value, label, Icon], index) => { const I = Icon as typeof Truck; return <div key={String(label)} className={`rounded-lg border p-4 text-center ${index === 5 ? "border-primary/20 bg-primary/5" : "border-outline bg-surface-low"}`}><div className={`kpi ${index === 5 ? "text-primary" : "text-ink"}`}>{String(value)}</div><div className="eyebrow mt-2 flex items-center justify-center gap-1"><I size={14} />{String(label)}</div></div>; })}</div>
            <div className="relative flex min-h-[180px] flex-1 items-center justify-between rounded-lg border border-outline px-5 pt-7"><span className="eyebrow absolute left-4 top-3">Network Flow</span><div className="absolute left-[12%] right-[12%] top-[56%] h-0.5 bg-outline" />{[[Truck, "Suppliers"], [Factory, "Factory"], [Warehouse, "Warehouses"], [Store, "Stores"]].map(([Icon, label], index) => { const I = Icon as typeof Truck; return <div key={String(label)} className="relative z-10 flex w-[72px] flex-col items-center gap-2 rounded-lg border border-outline bg-white p-2 text-center shadow-sm"><div className={`grid rounded-full ${index === 1 ? "h-12 w-12 bg-primary text-white ring-4 ring-primary/10" : "h-10 w-10 bg-secondary-soft text-muted"} place-items-center`}><I size={20} /></div><span className="mono text-[9px] font-semibold uppercase">{String(label)}</span></div>; })}</div>
          </section>
        </div>
      </>}
      {(run.isError || simulation.data?.status === "failed") && <p role="alert" className="mb-4 text-sm text-danger">{run.error?.message ?? simulation.data?.error?.message ?? "Simulation failed."}</p>}
      {step >= 0 && (step < progressSteps.length || simulation.data?.status === "queued" || simulation.data?.status === "processing") && <div className="fixed inset-0 z-[70] grid place-items-center bg-background/80 p-4 backdrop-blur-sm" role="status" aria-live="polite"><div className="card w-full max-w-sm p-6 text-center"><Network className="mx-auto mb-3 animate-pulse text-primary" size={32} /><h2 className="section-title">Analyzing Disruption Impactâ€¦</h2><p className="my-4 text-sm text-muted">{progressSteps[step] ?? "Waiting for backend processing"}</p><div className="h-1.5 overflow-hidden rounded-full bg-surface-high"><div className="h-full rounded-full bg-primary transition-all duration-300" style={{ width: `${Math.min(((step + 1) / progressSteps.length) * 100, 100)}%` }} /></div><div className="mono mt-2 text-[10px] text-muted">{step < progressSteps.length ? `Step ${step + 1} of ${progressSteps.length}` : "Backend processing"}</div></div></div>}
    </div>
  </AppShell>;
}
