import { z } from "zod";

const unit = z.enum(["g", "kg", "ml", "l", "pcs"]);
export const apiRiskLevelSchema = z.enum(["LOW", "MEDIUM", "HIGH", "STOCKOUT"]);
const instant = z.iso.datetime({ offset: true });
const pagination = z.object({ page: z.number(), pageSize: z.number(), totalItems: z.number(), totalPages: z.number() });
export const productsResponseSchema = z.object({ products: z.array(z.object({ id: z.string(), name: z.string(), price: z.number().int().nonnegative(), currency: z.literal("IDR"), isActive: z.boolean() })) });
const transactionSummary = z.object({ id: z.string(), createdAt: instant, totalItems: z.number().int(), totalAmount: z.number().int(), currency: z.literal("IDR") });
export const transactionsResponseSchema = z.object({ items: z.array(transactionSummary), pagination });
export const transactionResponseSchema = z.object({ transaction: transactionSummary.extend({
  items: z.array(z.object({ productId: z.string(), productName: z.string(), quantity: z.number().int(), unitPrice: z.number().int(), subtotal: z.number().int() })),
  ingredientConsumption: z.array(z.object({ ingredientId: z.string(), ingredientName: z.string(), quantity: z.number(), unit })),
}) });
export const inventoryResponseSchema = z.object({ inventoryVersion: z.number().int().nonnegative().optional(), items: z.array(z.object({ ingredientId: z.string(), ingredientName: z.string(), category: z.string().nullable(), currentStock: z.number(), unit, predictedRequirement: z.number(), requirementHorizonDays: z.literal(3), riskLevel: apiRiskLevelSchema, riskReason: z.string(), updatedAt: instant })) });
export const movementsResponseSchema = z.object({ items: z.array(z.object({ id: z.string(), ingredientId: z.string(), ingredientName: z.string(), type: z.enum(["SALE", "STOCK_IN", "ADJUSTMENT", "WASTE", "DAMAGE"]), quantityChange: z.number(), unit, transactionId: z.string().nullable(), note: z.string().nullable(), createdAt: instant })), pagination });
export const risksResponseSchema = z.object({ generatedAt: instant, horizonDays: z.literal(3), items: z.array(z.object({ ingredientId: z.string(), ingredientName: z.string(), unit, currentStock: z.number(), incomingStock: z.number(), predictedRequirement: z.number(), projectedStock: z.number(), safetyStock: z.number(), reorderPoint: z.number(), leadTimeHours: z.number(), riskLevel: apiRiskLevelSchema, riskReason: z.string(), projectedStockoutDate: z.iso.date().nullable().optional() })) });
export const forecastResponseSchema = z.object({ product: z.object({ id: z.string(), name: z.string() }), horizonDays: z.literal(3), generatedAt: instant, model: z.object({ name: z.string(), version: z.string() }), history: z.array(z.object({ date: z.iso.date(), actualDemand: z.number().int(), historySource: z.string().nullable().optional() })), forecast: z.array(z.object({ date: z.iso.date(), horizon: z.number().int(), predictedDemand: z.number().int() })), ingredientRequirements: z.array(z.object({ ingredientId: z.string(), ingredientName: z.string(), totalRequired: z.number(), unit })), source: z.enum(["XGBOOST", "FALLBACK"]).nullable().optional(), isSynthetic: z.boolean().nullable().optional(), trainingDataSynthetic: z.boolean().nullable().optional(), fallbackReason: z.string().nullable().optional() });
const procurementRecommendationSchema = z.object({ id: z.string(), ingredientId: z.string(), ingredientName: z.string(), unit, currentStock: z.number(), predictedRequirement: z.number(), safetyStock: z.number(), projectedStock: z.number(), riskLevel: apiRiskLevelSchema, recommendedOrderQuantity: z.number().positive(), receivedQuantity: z.number().nonnegative().optional(), outstandingQuantity: z.number().nonnegative().optional(), planId: z.string().optional(), recommendedOrderAt: z.iso.date(), supplier: z.object({ id: z.string(), name: z.string(), leadTimeHours: z.number() }), status: z.enum(["PENDING", "APPROVED", "REJECTED"]), explanation: z.object({ text: z.string(), source: z.enum(["QWEN", "FALLBACK"]) }), expectedArrivalAt: instant.nullable().optional(), estimatedCost: z.number().nullable().optional() });
export const procurementResponseSchema = z.object({ generatedAt: instant, optimizerStatus: z.enum(["OPTIMAL", "FEASIBLE", "INFEASIBLE", "ERROR"]), planOutcome: z.enum(["COMPLETE", "PARTIAL", "INFEASIBLE"]).nullable().optional(), totalEstimatedCost: z.number().nullable().optional(), limitations: z.array(z.string()).optional(), recommendations: z.array(procurementRecommendationSchema), outstandingRecommendations: z.array(procurementRecommendationSchema).default([]) });
export const dashboardResponseSchema = z.object({ generatedAt: instant, today: z.object({ revenue: z.number(), currency: z.literal("IDR"), transactions: z.number(), productsSold: z.number() }), inventory: z.object({ atRiskIngredientCount: z.number(), activeRecommendationCount: z.number() }), priorityActions: z.array(z.object({ recommendationId: z.string(), ingredientId: z.string(), ingredientName: z.string(), riskLevel: apiRiskLevelSchema, recommendedOrderQuantity: z.number(), unit, recommendedOrderAt: z.iso.date(), summary: z.string() })) });
export const decisionRequestSchema = z.object({ decision: z.enum(["APPROVED", "REJECTED"]) });
export const decisionResponseSchema = z.object({ id: z.string(), status: z.enum(["PENDING", "APPROVED", "REJECTED"]), reviewedAt: instant });
export const adjustmentRequestSchema = z.object({ expectedInventoryVersion: z.number().int().nonnegative(), countedStock: z.number().nonnegative(), unit, reason: z.enum(["PHYSICAL_COUNT", "WASTE", "DAMAGE", "OTHER"]), note: z.string().nullable() });
export const receivingRequestSchema = z.object({ quantity: z.number().positive(), unit, supplierId: z.string().min(1), note: z.string().nullable(), recommendationId: z.string().optional(), externalReceiptId: z.string().min(1) });
const snapshot = z.object({ ingredientId: z.string(), ingredientName: z.string(), currentStock: z.number(), unit, updatedAt: instant });
export const adjustmentResponseSchema = z.object({ inventory: snapshot, movement: z.object({ id: z.string(), type: z.string(), quantityChange: z.number(), unit, createdAt: instant }).nullable() });
export const receivingResponseSchema = z.object({ inventory: snapshot, movementId: z.string() });
export const shortageResponseSchema = z.object({ shortages: z.array(z.object({ ingredientId: z.string(), requiredBase: z.number(), availableBase: z.number(), shortfallBase: z.number() })) });
export type ApiRiskLevel = z.infer<typeof apiRiskLevelSchema>;
